### ISSUE TITLE
1.Fork scaffold-eth

### ISSUE THREAD

**Issue by giorgosn** [giorgosn/Decentralized-social-media-account#1]
Fork Scaffold-eth from master.
Check that everything is working correctly.

**Comment by TreBlack** [comment]
Hello @giorgosn ! This sounds like an interesting project based on the one line description. Could you elaborate on what problem you are looking to solve with this project?

**Comment by giorgosn** [comment]
Hey @OdellBIII 
You can take a look at the wiki I have added some information there.
The idea is let coin holders vote on what will be post in a twitter or other social account.
My original thought is music songs that are under-valued and there are not promoting so much from the youtube algorith.
But this idea has a lot of applications.
Do you have any specific question?

**Comment by giorgosn** [comment]
Thank you for the pull request and your time! 
No I haven't any agreement from any DAO but I know that something like this it can be really usefull.
I know that there are a lot of social media accounts that are being opereted by DAO members but still not in so dynamic way.
If you are interested to talk more you can join to this discord server:
https://discord.gg/XVr28rDhmY

**Comment by OdellBIII** [comment]
Thank you for the invitation

**Comment by OdellBIII** [comment]
Do you mind closing this issue?
