### ISSUE TITLE
2. Deploy a ERC20 token

### ISSUE THREAD

**Issue by giorgosn** [giorgosn/Decentralized-social-media-account#2]
Using the openzepeling contracts add the solidity smart contracts

Tips:
How to create a ERC20 token -> https://solidity-by-example.org/app/erc20/

Mini Tasks:

Send some tokens to other account.

**Comment by OdellBIII** [comment]
https://docs.openzeppelin.com/contracts/4.x/governance

Since this project is centered around getting people to vote on different proposals, I figured this document may be helpful

**Comment by OdellBIII** [comment]
I am currently working on making a basic ERC20 token, but maybe we can build on what I write and expand it to handle governance as well

**Comment by giorgosn** [comment]
I have check this out but for now we are thinking to use proposals from snapshot. It will be easier because we will have no gas cost.
Later it will be possible to use onchain governance.

**Comment by giorgosn** [comment]
Token were created on address: https://polygonscan.com/token/0x9fdf84885772f996185113baa9d86131d9b56bdf
