### ISSUE TITLE
Create a twitter account

### ISSUE THREAD

**Issue by giorgosn** [giorgosn/Decentralized-social-media-account#4]
This will be needed for the testing perpuses.

We will need to have a developer API code.

Examples on how to set up twitter API in JS https://vhudyma-blog.eu/post-a-tweet-using-twitter-api/

**Comment by OdellBIII** [comment]
Do you have specific email address you would like to attach to this twitter account?

**Comment by giorgosn** [comment]
I think it would be better for anyone to have its own test account.
In general I don't have any name in my mind. Any ideas are welcome @OdellBIII

**Comment by giorgosn** [comment]
Twitter handler is created https://twitter.com/kanariDAO
