### ISSUE TITLE
Set up the ENS name

### ISSUE THREAD

**Issue by giorgosn** [giorgosn/Decentralized-social-media-account#6]

**Comment by OdellBIII** [comment]
Any suggestions for an ENS name?

**Comment by giorgosn** [comment]
@OdellBIII  I buy a ENS and I have started creating the social that we will test and some basic branding.
Did not think too much the name and the logo. Later that we will have better stracture and a DAO for taking actions we will vote for rebranding

**Comment by OdellBIII** [comment]
What is the ENS name you chose? I am going to work on setting up the snapshot space and I need the ENS name

**Comment by giorgosn** [comment]
I used the kanari.eth @OdellBIII  ( its temporery)
you can check this site too kanari.eth.link 
The snapshot page is here https://snapshot.org/#/kanari.eth
and we created a erc20 token for testing. If you send me your address I can send you some.
Here is the contract address https://polygonscan.com/address/0x9fdf84885772f996185113baa9d86131d9b56bdf
